version: 1.0.{build}
environment:
  npm_auth_token:
    secure: KmGCxTofeoh15UJ0SlPXexXcPWxFNMYQaMVanbSvhY/oFrZGmow84e0bgfE9syZj
install:
- ps: >-
    Install-Product node $env:STABLE


    npm install


    "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

    npm whoami
build_script:
- cmd: >-
    npm --no-git-tag-version version %APPVEYOR_BUILD_VERSION%

    npm pack
test_script:
- cmd: >-
    node --version

    npm --version


    npm test
artifacts:
- path: skeddly-sdk-*.tgz
deploy_script:
- cmd: npm publish