version: 1.0.{build}
environment:
  npm_auth_token:
    secure: 51vUqemirykPBLPWrLbAiKD6PAiGOsyl8QbsQue9HCWgzWpn9D+XGN23sZrfBmdg
install:
- ps: >-
    Install-Product node $env:STABLE


    npm install

    Write-host $env:npm_auth_token

    Set-Content -Value "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" -Path "$env:userprofile\.npmrc"

    Write-Host "$env:userprofile\.npmrc"
    
    npm whoami
build_script:
- cmd: >-
    npm --no-git-tag-version version %APPVEYOR_BUILD_VERSION%

    npm pack
test_script:
- cmd: >-
    node --version

    npm --version


    npm test
artifacts:
- path: skeddly-sdk-*.tgz
deploy_script:
- cmd: npm publish