version: 1.0.{build}
skip_tags: true
environment:
  npm_auth_token:
    secure: GZ42D+k/3zSBFKMdRl+EyjcIk8+b9k6IbU5Hf2Z4bV2lUg9CokQmdp3D1dRNR2Zc
install:
- ps: >-
    Install-Product node $env:STABLE


    npm install

    Set-Content -Value "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" -Path "$env:userprofile\.npmrc"

    npm whoami
build_script:
- cmd: >-
    npm --no-git-tag-version version %APPVEYOR_BUILD_VERSION%

    npm pack
test_script:
- cmd: >-
    node --version

    npm --version


    npm test
artifacts:
- path: skeddly-sdk-*.tgz

# here we are going to override common configuration
for:

# override settings for `master` branch
- 
    branches:
        only:
        - master

    deploy_script:
    - cmd: npm publish